# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# Results can be witnessed at: https://circleci.com/gh/marshall62/partner
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
    - image: circleci/python:3.8.5

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
#     - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
#    - restore_cache:
#        keys:
#        - v1-dependencies-{{ checksum "requirements.txt" }}
#        # fallback to using the latest cache if no exact match is found
#        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - run:
        name: run tests
        command: |
          . venv/bin/activate
#          export FLASK_ENV=testing
#  DATABASE_URL is checked by ProductionConfig so set to empty value so it doesn't fail.
          exort DATABASE_URL=
#          This config will use SQLite database.
          export APP_SETTINGS=app_settings.TestingConfig
          python -m pytest tests

    - store_artifacts:
        path: test-reports
        destination: test-reports