"""empty message

Revision ID: d7809cbdd340
Revises: 
Create Date: 2020-01-03 19:09:39.152479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7809cbdd340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=12), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=12), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_number'), 'section', ['number'], unique=False)
    op.create_index(op.f('ix_section_term'), 'section', ['term'], unique=False)
    op.create_index(op.f('ix_section_title'), 'section', ['title'], unique=False)
    op.create_index(op.f('ix_section_year'), 'section', ['year'], unique=False)
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onecard_id', sa.String(length=12), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('nick_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['roster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_first_name'), 'student', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_last_name'), 'student', ['last_name'], unique=False)
    op.create_index(op.f('ix_student_nick_name'), 'student', ['nick_name'], unique=False)
    op.create_index(op.f('ix_student_onecard_id'), 'student', ['onecard_id'], unique=True)
    op.create_table('attendance_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('value', sa.String(length=12), nullable=True),
    sa.Column('stud_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stud_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_entry_date'), 'attendance_entry', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_entry_timestamp'), 'attendance_entry', ['timestamp'], unique=False)
    op.create_table('group2student',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group2student')
    op.drop_index(op.f('ix_attendance_entry_timestamp'), table_name='attendance_entry')
    op.drop_index(op.f('ix_attendance_entry_date'), table_name='attendance_entry')
    op.drop_table('attendance_entry')
    op.drop_index(op.f('ix_student_onecard_id'), table_name='student')
    op.drop_index(op.f('ix_student_nick_name'), table_name='student')
    op.drop_index(op.f('ix_student_last_name'), table_name='student')
    op.drop_index(op.f('ix_student_first_name'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    op.drop_table('group')
    op.drop_table('roster')
    op.drop_index(op.f('ix_section_year'), table_name='section')
    op.drop_index(op.f('ix_section_title'), table_name='section')
    op.drop_index(op.f('ix_section_term'), table_name='section')
    op.drop_index(op.f('ix_section_number'), table_name='section')
    op.drop_table('section')
    # ### end Alembic commands ###
